In [57]:
%run encode.ipynb
x = df_encoded.drop(
    columns=[
        "price_eur",
        "asin",
        "title",
        "product_url",
        "search_page"
    ],
    errors="ignore"
)

y = df_encoded["price_eur"]

         asin                                              title  price_eur  \
0  B0G71BJS8S  Microsoft Surface Laptop, 13.8" | Snapdragon X...    1056.07
1  B0DYDVFVTJ  Microsoft Surface Laptop, 13" | Snapdragon X P...     735.54
2  B0F8L98RLY  HP Laptop | 15,6" FHD Display | Intel N100 | 4...     219.00
3  B0H28V9JGR  Laptop 15,6 Zoll 8GB RAM 256GB SSD Notebook Fu...     249.19
4  B0DJBQ8Y7K  HP Chromebook x360 Laptop (14" HD Touchscreen,...     219.00

   rating  reviews  ram_gb  storage_gb  screen_size_inch  touchscreen  gaming  \
0     4.8     15.0    16.0       512.0              13.8        False   False
1     4.3     74.0    16.0       256.0              13.0        False   False
2     4.1    170.0     4.0       128.0              15.6        False    True
3     4.2      8.0     8.0       256.0              15.6        False    True
4     4.2    181.0     4.0       128.0              14.0         True    True

   ... resolution_2560x1600  resolution_2880x1620  resolution_2880x1800  \
0  ...                False                 False                 False
1  ...                False                 False                 False
2  ...                False                 False                 False
3  ...                False                 False                 False
4  ...                False                 False                 False

   resolution_3120x2080  resolution_3270x2180  resolution_3456x2234  \
0                 False                 False                 False
1                 False                 False                 False
2                 False                 False                 False
3                 False                 False                 False
4                 False                 False                 False

   resolution_3840x2160  resolution_3840x2400  resolution_Unknown  \
0                 False                 False                True
1                 False                 False                True
2                 False                 False               False
3                 False                 False               False
4                 False                 False               False

   resolution_nan
0           False
1           False
2           False
3           False
4           False

[5 rows x 249 columns]
(277, 249)

In [58]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score

x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

model.fit(x_train, y_train)

y_pred = model.predict(x_test)

print("MAE:", mean_absolute_error(y_test, y_pred))
print("R²:", r2_score(y_test, y_pred))

MAE: 332.8215928571427
R²: 0.4988677893735807

In [4]:
print(y.isna().sum())
print(x.isna().sum().sum())

0
0

In [47]:
print(df_encoded[["price_eur", "ram_gb", "storage_gb", "screen_size_inch", "rating"]].describe())

         price_eur      ram_gb   storage_gb  screen_size_inch      rating
count   278.000000  278.000000   278.000000        278.000000  278.000000
mean    889.513201   19.618705   785.453237         15.560791    4.310432
std     738.528506   12.195102   904.669134          1.472568    0.707923
min      89.200000    4.000000   128.000000          8.000000    1.000000
25%     387.177500   16.000000   512.000000         14.000000    4.000000
50%     693.895000   16.000000   512.000000         15.600000    4.400000
75%    1165.630000   30.000000  1024.000000         16.000000    5.000000
max    6299.590000   96.000000  8192.000000         18.500000    5.000000

In [59]:
print(df.describe(include="all").T)

                  count unique  \
asin                277    277
title               277    276
brand               277     47
price_eur         277.0    NaN
rating            277.0    NaN
reviews           277.0    NaN
cpu                 277    106
ram_gb            277.0    NaN
storage_gb        277.0    NaN
gpu                 277     39
screen_size_inch  277.0    NaN
resolution          277     20
os                  277     14
keyboard            277      5
touchscreen         277      2
gaming              277      2
product_url         270    270
search_page       277.0    NaN

                                                                top freq  \
asin                                                     B0G71BJS8S    1
title             jumper 17,6 Zoll Laptop 16GB RAM 256GB SSD für...    2
brand                                                          Acer   49
price_eur                                                       NaN  NaN
rating                                                          NaN  NaN
reviews                                                         NaN  NaN
cpu                                                    Intel Core 5   12
ram_gb                                                          NaN  NaN
storage_gb                                                      NaN  NaN
gpu                                              Intel UHD Graphics   56
screen_size_inch                                                NaN  NaN
resolution                                                1920x1080  134
os                                                  Windows 11 Home  125
keyboard                                                     QWERTZ  206
touchscreen                                                    True  139
gaming                                                         True  203
product_url       https://www.amazon.de/HP-Display-Graphics-Micr...    1
search_page                                                     NaN  NaN

                        mean         std    min     25%     50%      75%  \
asin                     NaN         NaN    NaN     NaN     NaN      NaN
title                    NaN         NaN    NaN     NaN     NaN      NaN
brand                    NaN         NaN    NaN     NaN     NaN      NaN
price_eur         889.408267  739.863134   89.2  386.67  691.81  1167.78
rating              4.310108    0.709183    1.0     4.0     4.4      5.0
reviews            46.927798  129.849251    0.0     2.0    10.0     39.0
cpu                      NaN         NaN    NaN     NaN     NaN      NaN
ram_gb             19.574007    12.19434    4.0    16.0    16.0     24.0
storage_gb        703.263538  467.943116  128.0   512.0   512.0   1024.0
gpu                      NaN         NaN    NaN     NaN     NaN      NaN
screen_size_inch   15.588087    1.403013   11.6    14.0    15.6     16.0
resolution               NaN         NaN    NaN     NaN     NaN      NaN
os                       NaN         NaN    NaN     NaN     NaN      NaN
keyboard                 NaN         NaN    NaN     NaN     NaN      NaN
touchscreen              NaN         NaN    NaN     NaN     NaN      NaN
gaming                   NaN         NaN    NaN     NaN     NaN      NaN
product_url              NaN         NaN    NaN     NaN     NaN      NaN
search_page         9.436823     5.51682    1.0     5.0     9.0     14.0

                      max
asin                  NaN
title                 NaN
brand                 NaN
price_eur         6299.59
rating                5.0
reviews            1200.0
cpu                   NaN
ram_gb               96.0
storage_gb         4096.0
gpu                   NaN
screen_size_inch     18.5
resolution            NaN
os                    NaN
keyboard              NaN
touchscreen           NaN
gaming                NaN
product_url           NaN
search_page          20.0

In [ ]:
Df[cpu].unice

In [49]:
print(df[df["ram_gb"] > 64][
    ["asin", "title", "ram_gb", "price_eur"]
])

print(df[df["storage_gb"] > 4096][
    ["asin", "title", "storage_gb", "price_eur"]
])

           asin                                              title  ram_gb  \
146  B0H75YMF3Y  MSI Titan 18 HX Draco Epic Gaming-Laptop, 18" ...    96.0

     price_eur
146    6299.59
           asin                                              title  \
206  B0GG4KB6R9  ASUS ExpertBook P1 | 15,6" FHD | Core 5 210H |...
212  B07WMR1XYN  ASUS Vivobook 17 | 17,3" FHD | Core 5 120U | R...
233  B0H2HSLB14  ASUS Vivobook 18 | 18" WUXGA | Ryzen AI 7 445 ...

     storage_gb  price_eur
206      8192.0     599.00
212      8192.0     554.37
233      8192.0    1159.00

In [51]:
print(df[df["screen_size_inch"] < 12][
    ["asin", "title", "screen_size_inch", "price_eur"]
])

           asin                                              title  \
26   B09MDGXHMF  HP Stream Laptop | 11,6" HD Display | Intel Ce...
95   B0FLTG2SXD  Dell Chromebook 11 3100 2-in-1 Notebook, 11,6-...
99   B0DQ16LS96  MSI Claw 8 AI+ Gaming Handheld, 8 Zoll FHD+ 12...
108  B0H1HQJ3SK  HP ProBook X360 11 G6 EE 2-in-1 Laptop, Full H...

     screen_size_inch  price_eur
26               11.6     299.89
95               11.6      89.20
99                8.0     918.58
108              11.6     145.22

In [44]:
df[df["screen_size_inch"] > 30][
    ["asin", "title", "screen_size_inch", "price_eur"]
]

,asin,title,screen_size_inch,price_eur
112,B0H5HS7LFQ,"Laptop 15,6 Zoll Rosa, AMD Ryzen 3000er-Serie,...",59.0,326.52

In [45]:
df[df["storage_gb"] == 0][
    ["asin", "title", "storage_gb", "price_eur"]
]

,asin,title,storage_gb,price_eur
116,B0836DLDD6,"Acer Aspire Go 16 (AG16-71P-96VZ) Laptop, 16"" ...",0.0,1132.00
159,B0836C6P46,"Acer Aspire 17 (A17-51M-97HQ) Laptop, 17"" FHD ...",0.0,1192.00
184,B0GPWBDZL1,"Acer Aspire 17, Laptop, Intel Core 7, 16GB RAM...",0.0,790.55

In [15]:
print(
    df[df["price_eur"] > 5000][
        ["title", "brand", "price_eur"]
    ].sort_values("price_eur", ascending=False)
)

                                                 title brand  price_eur
153  Acer Aspire 16 AI OLED, Laptop, Ultra 7, 32GB ...  Acer   97749.00
206  ASUS ExpertBook P1 | 15,6" FHD | Core 5 210H |...  ASUS   87562.00
116  Acer Aspire Go 16 (AG16-71P-96VZ) Laptop, 16" ...  Acer   62642.00
105  HP OmniBook X Flip, 16" WUXGA, AMD Ryzen AI 5,...    HP   61959.00
119  HP OmniBook 3 Laptop, 14" WUXGA, Snapdragon X,...    HP   61959.00
159  Acer Aspire 17 (A17-51M-97HQ) Laptop, 17" FHD ...  Acer   56032.00
233  ASUS Vivobook 18 | 18" WUXGA | Ryzen AI 7 445 ...  ASUS   51549.00
236  MSI Stealth A16 AI+ 16 Zoll 240Hz QHD+ OLED Ga...   MSI    6662.17
146  MSI Titan 18 HX Draco Epic Gaming-Laptop, 18" ...   MSI    6658.64
227  HP ProBook 4 G1a Notebook AI - 177-Grad Scharn...    HP    6593.00

In [29]:
print(
    df.loc[
        df["price_eur"] > 5000,
        ["asin", "title", "brand", "price_eur"]
    ].sort_values("price_eur", ascending=False)
)

           asin                                              title brand  \
146  B0H75YMF3Y  MSI Titan 18 HX Draco Epic Gaming-Laptop, 18" ...   MSI

     price_eur
146    6299.59

In [32]:
print(
    df.loc[
        df["price_eur"] < 200,
        ["asin", "title", "brand", "price_eur"]
    ].sort_values("price_eur")
)

           asin                                              title  \
138  B0GK96SLMR  HP OmniBook 3 Laptop, 17,3" FHD, AMD Ryzen AI ...
95   B0FLTG2SXD  Dell Chromebook 11 3100 2-in-1 Notebook, 11,6-...
29   B0CGLQJSXJ  Lenovo Chromebook IdeaPad Slim 3 | 14" Full HD...
108  B0H1HQJ3SK  HP ProBook X360 11 G6 EE 2-in-1 Laptop, Full H...
42   B0H98LRXVJ  Kayoote 2026 15,6" Laptop Win 11 Pro, 8GB RAM ...
269  B0GQGN48S5  Lenovo Thinkpad T460 Laptop Computer, Intel Co...
25   B0DD3SWKRK  Laptop 14 Zoll Win 11 Notebook 6GB RAM 256GB S...
6    B0HCHLSDT4  15,6 Zoll FHD Laptop, 16GB RAM 256GB SSD, Core...
27   B0H4GJKMDK  Lenovo ThinkPad X13 Gen 1 Business Laptop, 13,...
77   B0GRV8XZK9  HP ProBook 635 Aero G7 Laptop, 13,3 Zoll FHD(1...
264  B0H4G6QLJ9  Lenovo ThinkPad X13 Gen 1 Business Notebook, 1...
94   B0FCG26C7H  HP 15-fd0260ns Laptop, 39,6 cm (15,6 Zoll), FH...

              brand  price_eur
138              HP      32.98
95             Dell      89.20
29           Lenovo     133.89
108              HP     145.22
42          Kayoote     164.12
269  Amazon Renewed     170.14
25           NOTODD     171.85
6           Breloom     185.60
27   Amazon Renewed     188.18
77               HP     188.18
264  Amazon Renewed     188.18
94               HP     195.69

In [34]:
print(
    df.loc[
        df["price_eur"] < 100,
        ["asin", "title", "brand", "price_eur"]
    ].sort_values("price_eur")
)

          asin                                              title brand  \
95  B0FLTG2SXD  Dell Chromebook 11 3100 2-in-1 Notebook, 11,6-...  Dell

    price_eur
95       89.2

In [35]:
print(
    df.loc[
        (df["price_eur"] >= 100) & (df["price_eur"] < 200),
        ["asin", "title", "brand", "price_eur"]
    ].sort_values("price_eur")
)

           asin                                              title  \
29   B0CGLQJSXJ  Lenovo Chromebook IdeaPad Slim 3 | 14" Full HD...
108  B0H1HQJ3SK  HP ProBook X360 11 G6 EE 2-in-1 Laptop, Full H...
42   B0H98LRXVJ  Kayoote 2026 15,6" Laptop Win 11 Pro, 8GB RAM ...
269  B0GQGN48S5  Lenovo Thinkpad T460 Laptop Computer, Intel Co...
25   B0DD3SWKRK  Laptop 14 Zoll Win 11 Notebook 6GB RAM 256GB S...
6    B0HCHLSDT4  15,6 Zoll FHD Laptop, 16GB RAM 256GB SSD, Core...
77   B0GRV8XZK9  HP ProBook 635 Aero G7 Laptop, 13,3 Zoll FHD(1...
27   B0H4GJKMDK  Lenovo ThinkPad X13 Gen 1 Business Laptop, 13,...
264  B0H4G6QLJ9  Lenovo ThinkPad X13 Gen 1 Business Notebook, 1...

              brand  price_eur
29           Lenovo     133.89
108              HP     145.22
42          Kayoote     164.12
269  Amazon Renewed     170.14
25           NOTODD     171.85
6           Breloom     185.60
77               HP     188.18
27   Amazon Renewed     188.18
264  Amazon Renewed     188.18

In [36]:
print(
    df.loc[
        (df["price_eur"] >= 200) & (df["price_eur"] < 300),
        ["asin", "title", "brand", "price_eur"]
    ].sort_values("price_eur")
)

           asin                                              title  \
90   B0GZWZP385  Dell Latitude 5400 Laptop | 14 Zoll | 1920 x 1...
43   B0G4WG4WNX  14 Zoll Laptop, 8GB RAM, 128GB SSD, Celeron J4...
258  B0H8962NYN  HP ProBook 450 G5 Business Laptop, 15,6 Zoll F...
11   B0G43WRLBZ  Laptop 15,6 Zoll, 8 GB RAM 256 GB SSD, Full HD...
49   B0FX2Q7TBL  16-Zoll-Laptop,8GB DDR RAM, 256GB SSD tragbare...
4    B0DJBQ8Y7K  HP Chromebook x360 Laptop (14" HD Touchscreen,...
2    B0F8L98RLY  HP Laptop | 15,6" FHD Display | Intel N100 | 4...
28   B09BJQLYKM  ASUS Chromebook CX14 CX1405CTA-NK0438 | Laptop...
194  B0H29MQ52G  Energizer EnergyBook 15,6 Zoll FHD Laptop (Int...
3    B0H28V9JGR  Laptop 15,6 Zoll 8GB RAM 256GB SSD Notebook Fu...
262  B012SM9XF0  Toshiba Satellite P70-B-11R 43,9 cm (17,3 Zoll...
155  B0C7CS2NXV  2020 Microsoft Surface Laptop Go mit Intel Cor...
31   B0GY7XKC2D  Dell Latitude 5420 Business-Laptop, 14 Zoll (3...
39   B0DVM1KDW8  Asus Chromebook CX1405CKA#B0DVM1KDW8, Display ...
56   B0GYP3SKQ7  Lenovo ThinkPad X13 Gen 1 Business-Laptop, 13,...
148  B0GMPWKQNJ  14 Zoll FHD Laptop,Celeron J4105 Quad-Core,8GB...
12   B0F9LFB3HM  HP Laptop mit 17,3" HD+ Display, Intel Celeron...
19   B0GLQKSVHZ  Lenovo Laptop, 15,6" FHD Display, Intel N150, ...
255  B0F3D25JCK  Lenovo Thinkpad T14 Gen 1 Business Laptop, 14"...
87   B0F992BVWY  15,6 Zoll Laptop, 12th Quad Core N100 (bis zu ...
256  B0HFP3R7NH  Lenovo ThinkPad X13 Gen 1 Business Laptop 13,3...
123  B0GTLZ8775  Lenovo ThinkPad L13 Yoga Gen 2 Laptop, 2-in-1 ...
58   B0DS276GVH  Acer Aspire Lite AL15-32P-C9QZ Laptop, Noteboo...
26   B09MDGXHMF  HP Stream Laptop | 11,6" HD Display | Intel Ce...
134  B0C5N3W36N  HP Laptop | 15,6" FHD Display | Intel Celeron ...

              brand  price_eur
90   Amazon Renewed     201.93
43           Nmybwo     202.78
258  Amazon Renewed     207.00
11          Trygood     214.81
49        Morostron     214.81
4                HP     219.00
2                HP     219.00
28             ASUS     239.74
194       Energizer     239.87
3           Trygood     249.19
262         Toshiba     257.79
155  Amazon Renewed     261.13
31   Amazon Renewed     262.94
39             ASUS     265.52
56   Amazon Renewed     270.68
148          Rumtuk     274.96
12               HP     287.83
19           Lenovo     287.83
255  Amazon Renewed     287.86
87           Gezoon     291.30
256  Amazon Renewed     291.30
123          Lenovo     291.30
58             Acer     299.89
26               HP     299.89
134              HP     299.89

In [38]:
print(
    df.loc[
        (df["price_eur"] >= 300) & (df["price_eur"] < 500),
        ["asin", "title", "brand", "price_eur"]
    ].sort_values("price_eur").to_string(index=False)
)

      asin                                                                                                                                                                                                    title          brand  price_eur
B08L6N77H9                                                                         MEDION Avantum 17 E1e 43,9 cm (17,3 Zoll) Full HD Laptop (Intel N100, 4GB DDR4 RAM, 128GB SSD, HD Webcam, WLAN, Windows 11 Home)         MEDION     300.67
B0FMRQ91KM                               PC Portable 15,6 Zoll,N95 (bis zu 3,4 GHz),16GB DDR4 512GB SSD TF 1TB,Laptop Win 11,WiFi 5,USB 3.0,1920x1080 FHD,Gamer Computer Notebook,Klavier komplette Rückbeleuchtung       Beynivan     300.73
B0FMRRVM16                           PC Portable 15,6 Zoll,16GB DDR4 512GB SSD TF 1TB, Laptop Win 11,N95 (bis zu 3,4 GHz),1920x1080 FHD, WiFi 5, USB 3.0, Gamer Computer Notebook,Klavier komplette Rückbeleuchtung       BEYNIVAN     300.73
B0H1427K3T   2026 Laptop Computer Notebook QWERTY mit Deutscher Tastaturfolie,15.6" IPS FHD Display,8GB RAM 256GB SSD,Celeron N5100,WiFi5,BT5.0,USB3.0,Beleuchtete Tastatur,Fingerprint für Büro & Studenten,Silber        Molegar     300.74
B0H9WWGMTS                       Lenovo ThinkPad L13 Yoga Gen 2, Touchscreen 2-in-1 Business Laptop, Intel Core i5-1135G7, 13,3 Zoll FHD, 16GB RAM, 256GB SSD, UK QWERTY Tastatur, Windows 11 Pro (Generalüberholt)         Lenovo     308.49
B0GLPK7GP4 15,6 Zoll Laptop, Quad-Core N95(bis 3,4 GHz), 16GB RAM, 512GB SSD, Full-HD Display, beleuchtete Tastatur mit Nummernblock, 2,4G/5G WLAN, Bluetooth 5.0, Win 11 Notebook für Arbeit, Studium & Homeoffice       MAXLEGEN     309.34
B0H1WMB87Z                                                 HP ProBook 450 G7 Business Laptop, 15.6 Zoll (1366x768), Intel Core i5-10210U, 16GB RAM, 512GB SSD, US QWERTY Tastatur, Windows 11 Pro (Generalüberholt) Amazon Renewed     317.08
B0HH8MDSVC Auusda Laptop 15,6 Zoll Notebook, 16GB DDR4 RAM 512GB SSD, 3050E Prozessor, Fingerabdrucksensor, beleuchtete Tastatur, Ziffernblock, Privacy-Kameraabdeckung, leichtes Notebook für Schule & Büro,Silber         Auusda     317.28
B0H8Y5PQCT         Auusda Laptop 15,6 Zoll Notebook, 16 GB RAM, 512 GB SSD, Prozessor N5100(Beats N4120/5205U CPU), Fingerabdrucksensor, BT5.0, Wifi5, Privacy-Kameraabdeckung, leichtes Notebook für Schule & Büro         Auusda     317.94
B0FF4DH7YZ                               HP Elitebook 830 G8 Touchscreen-Business-Laptop, 13,3-Zoll-FHD-Notebook, Intel Core i7-1185G7, 16 GB RAM, 512 GB SSD, US QWERTY-Tastatur, Windows 11 Pro (generalüberholt) Amazon Renewed     325.67
B0GMQD788T     Lenovo Chromebook | Laptop | MediaTek | 4GB RAM| 128GB SSD | Ohne Netzteil | 14" WUXGA Display | MediaTek Kompanio 540 | 4GB RAM | 128GB UFS 2.2| ARM Mali-G57 MC3 Grafik | ChromeOS | QWERTZ | Blau         Lenovo     325.67
B0GSTYMGQ1                                          15.6 Zoll Laptop 16GB RAM 512GB ROM, AI-Unterstützung, AMD R5 (übertrifft i5-13420H, bis zu 3.6GHz), FHD Display Notebook, WiFi 6 USB 3.0, Full-Function Type-C         Liuord     326.52
B0H4GGW6M1                           15.6 Zoll Laptop, 16GB RAM 512GB SSD, AI-Unterstützung | AMD R5 (bis zu 3.6GHz), FHD Display Notebook, WiFi 6, Vollfunktions Type-C Ideal für Studium, Homeoffice und Business        MELIUNA     326.52
B0H5HS7LFQ                                  Laptop 15,6 Zoll Rosa, AMD Ryzen 3000er-Serie, 8 GB RAM, 256 GB SSD, Windows 11 Pro, FHD IPS Notebook, Wi-Fi 6, vollwertiges USB-C, Fingerabdruck, beleuchtete Tastatur        Trygood     326.52
B0GT1K4CPY                                          THEYETI Laptop 15.6 Zoll, 16GB RAM 512GB ROM,Enthaltene AI Copilot, AMD R5 (bis zu 3.6GHz), FHD Display Notebook, WiFi 6 USB 3.0 Full-Function Type-C (Schwarz)        THEYETI     326.52
B0GX7X7L57                                                 Energizer EnergyBook 18,5 Zoll Full HD Laptop (Intel P6500Y, 4GB RAM, 128GB SSD, 11 Home, Ultra Leise, 11h Akkulaufzeit) – WiFi AC, Bluetooth v4.2, Blau      Energizer     326.75
B0BBKYTKXR                                                                                                   ACER Chromebook 314 (CB314-6H-35T7) Laptop 14 Zoll | Intel Core i3 | 8 GB RAM | 128 GB eMMC | ChromeOS           Acer     335.62
B0DDCSBL87                 Lenovo IdeaPad 1 | Laptop | Ryzen 3 | 8GB | 512GB | 65W Netzteil | 15.6" Full HD Display | AMD Ryzen 3 7320U | 512GB SSD | 8GB RAM | AMD Radeon 610M Grafik | QWERTZ | Windows 11 | Grau         Lenovo     337.40
B0B1QDNQMF    Acer Aspire 1 A115-32-C3AK Ordinateur Portable 15.6" FHD (Intel® Celeron® N4500, Ram 4 Go, 128 Go eMMC, Intel UHD Graphic, Windows 11) - Clavier AZERTY, Laptop Gris + Microsoft 365 Personnel Inclus           Acer     342.86
B0GWQWHG9L              16 Zoll Business Laptop, 16GB RAM, 512GB SSD, Core i3 Prozessor | FHD IPS Display, Fingerabdruck, beleuchtete Tastatur, USB 3.0, WLAN, Type-C Charging, Grüner Notebook für, Arbeit, Schule         Nmybwo     343.71
B0DDCQJH2F                                     Lenovo IdeaPad 1 Laptop | 15.6" Full HD Display | AMD Ryzen 5 7520U | AMD Radeon Grafik | 16GB RAM | 512GB SSD | Win11 | QWERTZ | Cloud Grau | 3 Monate Premium Care         Lenovo     349.00
B0FBG2NT8T    Blackview Acebook 6 Laptop 15,6 Zoll für Unternehmen Studierende, Quad-Core N150(Besser N95) bis zu 3.6GHz, 16GB RAM 256GB SSD Notebook, FHD IPS Display Augenschutz, 100W Type-C, 4K HDMI, Bluetooth      Blackview     360.89
B0GP63VKQ5                                      Lenovo ThinkPad T14 Gen 2 14 Zoll 1920x1080 Full HD Intel Core i5 1145G7 256GB SSD Festplatte 16GB Speicher Windows 11 Pro Webcam Notebook Laptop (Generalüberholt) Amazon Renewed     360.90
B0DHYFQP59                            Lenovo IdeaPad Slim 3 Notebook 15,6 Zoll FHD (1920 x 1080), AMD Ryzen 3 7320U, RAM 8 GB, 256 GB SSD M.2, integrierte Grafik AMD Radeon 610M, WiFi 6, Windows 11 - Arctic Grey         Lenovo     360.90
B0H5PZXKB9        Auusda Laptop 15,6 Zoll Notebook, 16GB DDR4 RAM 512GB SSD, 3250C Prozessor, Fingerabdrucksensor, beleuchtete Tastatur, Ziffernblock, Privacy-Kameraabdeckung, leichtes Notebook für Schule & Büro         Auusda     368.53
B0G1FZ5F8N           CYCLUS 16" Laptop für Studenten, Büro & Kreative – AMD Ryzen 5 3500U (4C/8T 3,7 GHz), 16GB RAM, 512GB SSD, Vega 8, USB-C, Tastatur mit Hintergrundbeleuchtung + QWERTZ-Tastaturfolie inklusive         CYCLUS     368.64
B0H5CPVX3Y              Molegar 15,6 Zoll FHD IPS Süß Laptop Roségold | Ryzen 3 3000 Serie bis 3,5 GHz | 8GB DDR4 256GB SSD | Beleuchtete Tastatur Fingerabdruck | WiFi 6 BT5.2 Type-C | Tragbar für Büro & Studium        Molegar     369.49
B0FCG2VS1T                                         HP Laptop 39,6 cm (15,6 Zoll) FHD (AMD Ryzen 5-7520U, 16 GB RAM, 1 TB SSD, AMD Radeon Graphics, ohne Betriebssystem), Silber und Blau, spanische QWERTY-Tastatur             HP     376.30
B0GTWGHSC9                                                              Energizer EnergyBook 18,5 Zoll FHD Laptop (Intel P6500Y, RAM 8 GB, SSD 256 GB, Intel UHD Graphics 615, Win 11 Home) – QWERTY-Tastatur, grau      Energizer     378.39
B0CYT8KDX9                                                                    2021 Microsoft Surface Laptop 4 mit Intel Core i7-1185G7 (13,5-zoll, 16GB RAM, 256GB SSD) (QWERTY Englisch) Schwarz (Generalüberholt) Amazon Renewed     379.71
B0G2SX5G3J             Lenovo IdeaPad Slim 3 | Laptop | Ryzen 3 | 8GB | 512GB | Ohne Netzteil | 15.6" Full HD Display | AMD Ryzen 3 30 | 512GB SSD | 8 GB RAM | AMD Radeon 610M Grafik | QWERTZ | Windows 11 | Blau         Lenovo     385.82
B0GRV9LRCZ                                                  HP ZBook Firefly 14 G9 Workstation Laptop, 14 Zoll FHD Display, Intel Core i5-1250P, 16GB RAM, 512GB SSD, US QWERTY Tastatur, Windows 11 Pro (erneuert)             HP     385.82
B0G6WVQKMR                                 16 Zoll FHD Gaming Laptop mit AMD Ryzen 7 4800H 8-Kern-Prozessor, 16GB DDR4 RAM, 512GB SSD, AMD Radeon Graphics, Wi-Fi 6, IPS Bildschirm, 65W Typ-C, Fingerabdrucksensor        Breloom     386.67
B0GT2P1D4D                   ACEMAGIC AMD Laptop, AMD Ryzen 7 5000 Series (8C/16T), Radeon RX Vega 8 Graphics, 16.1 Zoll FHD Display, 16GB RAM, 512GB NVMe SSD mit Numeric KB, Type_C (Full Function), WiFi 6, Akku       ACEMAGIC     388.70
B0GPSX4BWX                                                                                   ASUS Vivobook Go 15 Notebook 15,6" FHD 60Hz mit Intel N150 Prozessor, Intel UHD Grafik, 8GB RAM, 128GB SSD, Kaltsilber           ASUS     394.14
B0GQZ7XCYR       CYCLUS 16" Laptop für Studenten, Büro & Alltagsnutzung – AMD Ryzen 5 3500U (4C/8T 3,7 GHz), 16GB RAM, 1TB SSD, Vega 8, USB-C, Tastatur mit Hintergrundbeleuchtung + QWERTZ-Tastaturfolie inklusive         CYCLUS     394.41
B0GR4YF4JG     jumper Laptop 17,6 Zoll, Celeron Quad core, 16GB RAM 512GB SSD + 128GB eMMC | 100% sRGB FHD Display, Enthält Office 365, QWERTZ Leuchtende Tastatur, 7000mAh, Notebook für Studenten und Unternehmen         jumper     395.26
B0CN9QRP11                                                                                                                  Lenovo ThinkPad T14 Gen 1 14" FHD i5-10310U 16GB 256GB SSD Win 11 Pro (Generalüberholt) Amazon Renewed     399.99
B0GQT9GTFR       2-in-1 Touchscreen Laptop 16 Zoll, Ryzen 3 3300U, 16GB RAM, 512GB SSD | 360° Convertible, Fingerabdrucksensor, Beleuchtete Tastatur, WiFi 6, Bluetooth 5.2, IPS FHD, USB-C Multifunktionsanschluss           BTDD     400.42
B0GR4NTZQ9                                              Lenovo Thinkpad T14s Gen 3 Business Laptop, 14 Zoll FHD (1920x1080), Intel Core i7-1270, 16GB RAM, 512GB SSD, US QWERTY Tastatur, Windows 11 Pro (erneuert)         Lenovo     403.01
B0H8HP8KK8                   Lenovo ThinkPad T14s Gen 1 Business-Laptop, 14 Zoll FHD (1920 x 1080), Intel Core i7-10610U, 32 GB RAM, 1 TB SSD, japanische QWERTY-Tastatur, Webcam, Windows 11 Pro (Generalüberholt) Amazon Renewed     403.01
B096XV7Y68                                                                                                           MSI Modern 15 B7M-463 15.6" Full HD Notebook AMD Ryzen 5 7430U 16 GB 512 GB SSD QWERTZ Schwarz            MSI     410.37
B0HBPJXKF4                                           17,6 Zoll Laptop, Core i3-10100Y, 16GB RAM 256GB SSD, Windows 11 | 1920x1200 FHD+ 16:10 Display, WiFi 6, Tastatur beleuchtet, Full-Featured Type-C,Mattschwarz          Unowo     411.60
B083L855NZ                 Acer Chromebook Plus 515| Laptop | Core i3 | 8GB | 128GB | mit Netzteil | 15,6" FHD IPS Display | Intel Core i3-1215U | 8GB RAM | 128GB SSD | Chrome OS | QWERTZ-Tastatur | CB515-2H-EU5           Acer     411.60
B0H1QT16ZV               jumper Laptop 17,6 Zoll, N95 CPU, 16GB RAM 512GB SSD + 128GB eMMC, 100% sRGB FHD Display, QWERTY Leuchtende Tastatur, mit Deutscher Tastaturfolie, 7000mAh, WiFi-6, Notebook für Studenten         jumper     412.44
B0H4G77SR4                      18,5 Zoll Laptop AI-Unterstützung 16GB RAM 256GB SSD | Core i3, Win 11, 8000mAh Akku, WiFi6, FHD, 180° Drehung, Vollfunktions Type-C, Deutsche Tastatur Ideal für Studium, Business        Meliuna     412.44
B0F8NN9W9H                       ACEMAGIC 18,5 Zoll Laptop,Twin Lake N150 (bis zu 3,6 GHz),8000mAh,16 GB DDR4 512 GB SSD bis zu 2 TB, 1920 x 1080 IPS Full HD Laptop, BT5.0, HDMI, Typ-C, 180° Öffnen und Schließen       ACEMAGIC     412.44
B0HBWH4865         jumper Laptop 16 Zoll, IPS FHD Touchscreen Laptops, 16GB RAM 640GB Storage | Fingerabdruckleser, N5095 CPU, 1 Jahr Office 365, Tastatur mit Hintergrundbeleuchtung, WiFi, für Studenten Business         jumper     429.64
B0FVXKWYTK                                                                  Gaming Laptop | 15,6 Zoll Notebook | AMD Ryzen 7 7730U | Bis zu 4.5GHz|16GB RAM | 512GB SSD | AMD Radeon | NVMe PCIe 3.0 | WiFi6 | HDMI        Tivique     429.64
B0GMFR2ZRL              17,3 Zoll Laptop,16GB DDR4 RAM,1TB SSD,4-Kern N150 bis zu 3,6 GHz | Beat N95 N5095,FHD IPS Display,Lange Akkulaufzeit, Beleuchtete Tastatur,Ziffernblock,Webcam,WiFi/Bluetooth/USB 3.0,Grau        Unknown     437.38
B0FZQDC2X8                 16 Zoll FHD Laptop Lila, 1TB SSD, 16GB DDR4 RAM, Quad-Core N95 CPU | bis zu 3.4GHz(Beat N5095 N4120), Face Unlock, Farb-Tastatur, HDMI, USB 3.0, Type-C, WLAN, 5000mAh Notebook Computer          Fsjun     438.23
B0FCG26C7H                                   HP 15-fd0260ns Laptop, 39,6 cm (15,6 Zoll), FHD (Intel Core i3-N305, 8 GB RAM, 512 GB SSD, Intel UHD Graphics, ohne Betriebssystem), Silber, spanische QWERTY-Tastatur             HP     449.00
B0H829J7MZ      15,6" FHD Laptop|Ryzen 7 8-Kern|16 GB DDR4|512 GB NVMe-mit Netzteil | Metallgehäuse|Fingerprint|WiFi|BT5.0|USB 3.0|Type-C (vollwertig)|Beleuchtete Tastatur|Notebook PC für Gaming Schüler und Büro         Rumtuk     455.42
B0H6Q4RH55  jumper 17,6 Zoll Laptop 16GB RAM 256GB SSD für Unternehmen und Studenten | 100% sRGB FHD Display, 10100Y CPU(bis zu 3,9GHz), Beleuchtetes QWERTZ-Tastatur Notebook Computer, Allgemein Typ-C/HDMI/WiFi6         Jumper     464.00
B0GQ5JZHCJ                                 Lenovo ThinkPad L15 Gen 2 Ryzen 5 Pro 6 x 2.3 GHz Prozessor, 16 GB Arbeitsspeicher, 512 GB SSD, 15.6 Zoll Display, Full HD 1920 IPS Windows 11 Pro H9K (Generalüberholt) Amazon Renewed     476.91
B0FWHMRPGQ    17,3 Zoll Laptop, 16GB RAM, 1TB SSD, 6500Y CPU bis zu 3,40 GHz über 3250C | FHD IPS Display, Fingerabdruck, Backlit-Tastatur, HDMI, WLAN, Business Notebook für Büro, Studium, Home, DE Tastaturfolie          Fsjun     480.33
B0F38Q1245                                                                       2021 Microsoft Surface Laptop 4 mit Intel Core i7-1185G7 (13,5-zoll, 32GB RAM, 1TB SSD) (QWERTY Englisch) Silber (Generalüberholt) Amazon Renewed     487.12
B0DS2LB2DT         Acer Aspire Go 15 | Laptop | Ryzen 7 | 16GB | 512GB | mit Netzteil | 15,6" FHD IPS Display | AMD Ryzen 7 5825U | 16GB RAM | 512GB SSD | AMD Grafik| Windows 11 | QWERTZ Tastatur | AG15-42P-R8SZ           Acer     488.94
B0CGDJ67QR  Acer Nitro V 15 ANV15 – 51 – 5673 Notebook Gaming, Prozessor Intel Core i5 – 13420H, RAM 16 GB DDR5, 512 GB SSD, Display 15,6 Zoll FHD IPS 144 Hz LED LCD, Nvidia GeForce RTX 4050 6 GB Windows 11 Home           Acer     488.94
B0F9YYDDFD                                Dell 15 Laptop DC15250 15.6" FHD (1920 x 1080) 120Hz, Intel Core i7-1355U, Intel UHD Graphics, 16GB DDR4 RAM, 512GB SSD, Windows 11 Home, QWERTZ Backlit Keyboard - Black           Dell     488.94
B0FV96S977             Acer Aspire 14 AI (A14-11M-X7MH) AI Laptop, Copilot+ PC, 14" WUXGA IPS 120Hz Display, Qualcomm Snapdragon X X1-26-100, 16 GB RAM, 512 GB SSD, Qualcomm Adreno GPU, Windows 11, QWERTZ Layout           Acer     488.94
B0BRCVH2NB                                                   Acer TravelMate P2 | 15,6" FHD | Core 5 120U | RAM: 16GB | SSD: 500GB | Laptop in Pure Silver | beleuchtete Tastatur | Windows 11 Pro | Notebooktasche           Acer     488.94
B0GMKQMG41                                  ASUS ExpertBook BM1 | 15,6" FHD | Ryzen 7 170 | RAM: 32GB | SSD: 2TB | Laptop in Gentle Grey | beleuchtete Tastatur | Windows 11 Pro | Office 2024 Pro | Notebooktasche           ASUS     488.94
B0CX5LKWMZ                               Acer Aspire 3 A315-59-36TH 15,6" ComfyView™ FHD IPS (matt) / Intel® Core™ i3-1215U / 8 GB DDR4 RAM / 512 GB SSD/Intel® UHD Graphics/Windows 11 Home (64 Bit) / Pure Silver           Acer     489.79
B0B8QYXY9H                                                                                               acer Aspire AG17-31P Laptop 17,3 Zoll Full HD, Intel N150, 8 GB RAM, 128GB | AZERTY Tastatur (Französisch)           Acer     497.48

In [40]:
# نمایش همه لپ‌تاپ‌های با قیمت بین 500 تا 1000 یورو

df_500_1000 = df[
    (df["price_eur"] >= 500) &
    (df["price_eur"] <= 1000)
].sort_values("price_eur")

print(df_500_1000[
    ["asin", "title", "brand", "cpu", "ram_gb", "storage_gb", "gpu", "price_eur"]
].to_string(index=False))

      asin                                                                                                                                                                                                    title             brand                                       cpu  ram_gb  storage_gb                     gpu  price_eur
B0FB7P7GF3                             Dell 16 Laptop DC16250 Intel Core 5 Series 1 16" 2K | Windows 11 Home, DDR5 RAM, 512 GB SSD, Graphics, spanische QWERTY-Tastatur mit Hintergrundbeleuchtung, Schwarz, WLAN 6              Dell               Intel Core 5 120U-Prozessor    16.0       512.0      Intel UHD Graphics     504.98
B0FJ64VF3N                         Lenovo ThinkPad L14 Gen 2 Ryzen 7 Pro 8 x 1.9 GHz Prozessor, 32 GB Arbeitsspeicher, 512 GB SSD, 14 Zoll Display, Full HD 1920x1080 IPS Windows 11 Pro 1920 P7K (Generalüberholt)    Amazon Renewed                           AMD Ryzen 7 Pro    32.0       512.0     AMD Radeon Graphics     514.71
B0F5Z2LCNT                                 Lenovo IdeaPad 3 Laptop | 17.3" Full HD Display | AMD Ryzen 5 5625U | 8GB RAM | 512GB SSD | AMD Radeon Grafik | Windows 11 | QWERTZ | Artic Grau | 3 Monate Premium Care            Lenovo                               AMD Ryzen 5     8.0       512.0       AMD Radeon Grafik     515.57
B0DRWB6FP9                                                                                                 Dell Business Laptop Notebook Latitude 3310 i3-8145u 8GB 256GB SSD 1366x768 Windows 11 (Generalüberholt)    Amazon Renewed                           Intel Core i3 8     8.0       256.0         NVIDIA RTX 5060     515.57
B0GR57VS6T          Gaming Laptop – 16 Zoll FHD Display Laptop mit AMD Ryzen 7 H255-Prozessor (Besser als I7-11800H) mit bis zu 4,9 GHz, 16 GB RAM DDR5 4800 MHz, 512 GB SSD, Gaming Notebook mit hintergrundbeleuc           Tivique        AMD Ryzen 7 Prozessorgeschwindkeit    16.0       512.0         AMD Radeon 780M     524.16
B0GMCYX8ND                          Lenovo ThinkPad T14 G1 Laptop | 14 Zoll | 1920 x 1080 | AMD Ryzen 5 Pro 4650U | 16 GB DDR4 RAM | 256 GB NVMe | DE-QWERTZ | Windows 11 Pro | 1 Jahr Garantie | (Generalüberholt)    Amazon Renewed                           AMD Ryzen 5 Pro    16.0       256.0      Intel UHD Graphics     529.31
B0FS1FRRB9        CYCLUS 15,6" Laptop R7 5825U (8C/16T bis 4,5 GHz), 16GB RAM, 1TB SSD | Für Studenten, Kreative & Gelegenheitsspieler, Vega 8, Tastatur mit Hintergrundbeleuchtung, QWERTZ-Tastaturfolie inklusive            CYCLUS                         AMD Ryzen 7 5825U    16.0      1024.0         AMD Radeon Vega     540.49
B0D5RFN7MG                                     HP EliteBook 850 G8 15,6 Zoll 1920x1080 Full HD Intel Core i5 1135G7 1TB SSD Festplatte 16GB Speicher Windows 11 Pro 4G LTE Webcam Notebook Laptop (Generalüberholt)    Amazon Renewed                   Intel Core i5 Prozessor    16.0      1024.0           Intel Iris Xe     549.09
B0GHZ5GYP4                                                  Dell 15 Laptop - Intel i5 1334U, 16GB DDR5, 512GB SSD | 15,6 Zoll FHD entspiegeltes Display, Windows 11 Home, Intel UHD Grafik, Deutsch QWERTZ Tastatur              Dell                       Intel Core i5-1334U    16.0       512.0      Intel UHD Graphics     549.09
B081D7N31K                              MSI Prestige 14 A10SC-009 (35,6 cm/14 Zoll/4K-UHD/100% Adobe RGB) Creator Laptop (Intel Core i7-10710U, 16GB RAM, 1TB PCIe SSD, Nvidia GeForce GTX1650 4GB, Windows 10 Pro)               MSI                      Intel Core i7-10710U    16.0      1024.0 NVIDIA GeForce GTX 1650     554.37
B07WMR1XYN                                   ASUS Vivobook 17 | 17,3" FHD | Core 5 120U | RAM: 16GB | SSD: 500GB | Laptop in Cool Silver | beleuchtete Tastatur | Windows 11 Pro | Office 2024 Pro | Notebooktasche              ASUS                         Intel Core 5 120U    16.0      8192.0           Intel Iris Xe     554.37
B0CP476MZ9                                  HP Laptop mit 17,3" FHD Display, AMD Ryzen 5 7520U, 16GB DDR5 RAM, 512 GB SSD, AMD Radeon-Grafik, Windows 11, QWERTZ, Silber inkl. 25 GB Dropbox-Speicher für 12 Monate                HP                              Intel Core 5    16.0       512.0 NVIDIA GeForce RTX 4070     556.67
B0FNRBBTD8                                             Acer Aspire Go 15 (AG15-72P-52M0) Laptop, 15,6" FHD IPS Display, Intel Core 5 120U, 16 GB RAM, 512 GB SSD, Intel Grafik, Windows 11, QWERTY Tastatur, Silber              Acer                              Intel Core 5    16.0       512.0          Intel Graphics     557.68
B0GPVPW64R                             Acer Aspire 17, Laptop, Intel Core 5, 16GB RAM, 1TB SSD | 17" FHD IPS Display, Intel Core 5 120U, 16GB RAM, 1TB SSD, Intel Grafik, Windows 11, QWERTZ Tastatur, A17-51M-55NU              Acer                              Intel Core 5    16.0      1024.0      Intel UHD Graphics     558.53
B0BV6S7P86                                         Acer Aspire 17 (A17-51M-503B) Laptop, 17" FHD IPS Display, Intel Core i5-1334U, 16 GB RAM, 512 GB SSD, Intel Iris Xe Graphics, Windows 11, QWERTZ Tastatur, grau              Acer                       Intel Core i5-1334U    16.0       512.0           Intel Iris Xe     558.53
B0F7LC6XHB                              acer Aspire Laptop, 14 Zoll WUXGA Touch IPS Display, Intel Ultra 5-226V, 8 Kerne, 16GB LPDDR5X RAM, 512GB PCIE SSD, BK, AI Copilot+PC, Webcam, Windows 11 Home, TWE Mauspad              Acer                   Intel Core Ultra 9 285H    16.0       512.0          Intel ARC 130V     562.56
B0H295NT2M        THEYETI 16 Zoll Touchscreen Laptop, Ryzen 3 3300U Prozessor(Beat N95) | 16GB RAM, 512GB SSD, QWERTZ-Tastatur mit Hintergrundbeleuchtung, Fingerabdruckleser, WiFi 6, BT 5.2, for Homeoffice, Büro           THEYETI                    Intel Core 5 Prozessor    16.0       512.0         AMD Radeon Vega     567.12
B0H69PD57W                                                               HP EliteBook 840 G8, 14” FHD Display, Intel Core i7 1185G7, 32GB RAM, 512GB SSD, Webcam, Windows 11 Pro, Notebook Laptop (Generalüberholt)    Amazon Renewed                      Intel Core i7 1185G7    32.0       512.0           Intel Iris Xe     571.43
B0GGRVPFRX                    Acer Extensa 15 Business Laptop, Core Ultra 5, 16GB RAM, 512GB SSD | 15,6" FHD IPS Display, Intel Core Ultra 5 115U, 16GB RAM, 512GB SSD, Intel Grafik, Windows 11 Pro, EXO15-51-573X              Acer              Intel Core Ultra 5 Processor    16.0      2048.0          Intel Graphics     571.84
B0GMR9FCWZ             Lenovo IdeaPad Slim 3 | Laptop | Ryzen 5 | 16GB | 512GB | Ohne Netzteil | 15.3" WUXGA Display | AMD Ryzen 5 150 | 512GB SSD | 16GB RAM | AMD Radeon 660M Grafik | QWERTZ | Windows 11 | Grau            Lenovo                           AMD Ryzen 5 150    16.0       512.0         AMD Radeon 660M     583.46
B0DTKK7JRN                 Samsung Galaxy Book4 Notebook, 15,6-Zoll-Display, Intel Core i3-Prozessor, 8 GB RAM, Laptop mit 256 GB Speicher, Gray, 3 Jahre Herstellergarantie, Windows 11 Home [Exklusiv auf Amazon]           Samsung                   Intel Core i3-Prozessor     8.0       256.0         NVIDIA RTX 4050     586.89
B0GG4KB6R9                                                                           ASUS ExpertBook P1 | 15,6" FHD | Core 5 210H | RAM: 32GB | SSD: 500GB | Laptop in Misty Grey | Windows 11 Pro | Notebooktasche              ASUS                         Intel Core 5 210H    32.0      8192.0                 Unknown     599.00
B0FV96S977             Acer Aspire 14 AI (A14-11M-X7MH) AI Laptop, Copilot+ PC, 14" WUXGA IPS 120Hz Display, Qualcomm Snapdragon X X1-26-100, 16 GB RAM, 512 GB SSD, Qualcomm Adreno GPU, Windows 11, QWERTZ Layout              Acer                         Intel Core 5 120U    16.0       512.0     Qualcomm Adreno GPU     599.00
B0DS2LB2DT         Acer Aspire Go 15 | Laptop | Ryzen 7 | 16GB | 512GB | mit Netzteil | 15,6" FHD IPS Display | AMD Ryzen 7 5825U | 16GB RAM | 512GB SSD | AMD Grafik| Windows 11 | QWERTZ Tastatur | AG15-42P-R8SZ              Acer                         AMD Ryzen 7 5825U    16.0       512.0       AMD Radeon Grafik     599.00
B0836QR869        Acer Aspire 16 AI | Laptop | Ryzen AI 5 | 16GB | 512GB | mit Netzteil | 16" 120Hz Display | AMD Ryzen AI 5 330 | 16GB RAM | 512GB SSD | Radeon 820M | Windows 11 | QWERTZ Keyboard | A16-61M-R98E              Acer                            AMD Ryzen AI 5    16.0       512.0         AMD Radeon 820M     600.64
B0FS1HF8LN               CYCLUS 15,6" Laptop R7 5825U (8C/16T bis 4,5 GHz), 32GB RAM, 1TB SSD | Für Profis, Kreative & leichtes Gaming, Vega 8, Tastatur mit Hintergrundbeleuchtung, QWERTZ-Tastaturfolie inklusive            CYCLUS                         AMD Ryzen 7 5825U    32.0      1024.0         AMD Radeon Vega     600.64
B0DX2X31XY                                   ASUS Vivobook 16 X1607QA | Laptop | Snapdragon X | 16GB | 512GB | 16" WUXGA | Snapdragon X X1-26-100 | Copilot+ PC | 16GB RAM | 512GB SSD | Win11 Home | ohne Netzteil              ASUS                        Intel Core Ultra 5    16.0       512.0 NVIDIA GeForce RTX 5060     600.64
B0FKC1WQ3K                 Lenovo IdeaPad Slim 3 | Laptop | Ryzen 5 | 24GB | 1TB | 65W Netzteil | 16" WUXGA Display | AMD Ryzen 5 7535HS | 1TB SSD | 24GB RAM | AMD Radeon 660M Grafik | QWERTZ | Windows 11 | Blau            Lenovo                        AMD Ryzen 5 7535HS    24.0      1024.0         AMD Radeon 660M     600.64
B0DLWYGGQW           Acer Swift 16 AI OLED (SF16-51-57H6) KI Laptop, Copilot+ PC, 16" WQ2.8K OLED 120Hz Display, Intel Core Ultra 5 226V, 16 GB RAM, 512 GB SSD, Intel Arc Grafik 130V, Windows 11, QWERTZ Tastatur              Acer                        Intel Core Ultra 5    16.0       512.0        Intel Arc Grafik     600.64
B0GJ3BNDBK HP OmniBook X Flip Laptop, 16" 2K, Intel Core Ultra 5, 16GB RAM, 512GB SSD | Copilot+ 2-in-1 KI Notebook mit Windows 11, wandelbar und mobil für Business und Streaming - ohne Ladegerät, QWERTZ, Silber                HP              Intel Core Ultra 5 Prozessor    16.0       512.0      Intel Arc Graphics     604.95
B0DNF8PNS7                                                      MEDION SPRCHRGD 14 S1 35,56 cm (14" Zoll 120Hz 2.8K WQXGA+) Laptop (Copilot+ PC, Qualcomm Snapdragon X Plus, 16GB DDR5 RAM, 512GB SSD, Win 11 Home)            MEDION                         Intel Core 7 150U    16.0       512.0                 Unknown     617.77
B0F8F3NNS6                                  Lenovo IdeaPad Slim 3i Laptop | 14" WUXGA Display | Intel Core i5 13420H | 16GB RAM | 512GB SSD | Intel UHD Grafik | Win11 | QWERTZ | Luna Grau | 3 Monate Premium Care            Lenovo                              Intel Core 5    16.0       512.0       AMD Radeon Grafik     622.21
B0CD2PG64B                                Lenovo IdeaPad Slim 3i Laptop | 14" Full HD Display | Intel Core i5-12450H | 16GB RAM | 512GB SSD | Intel UHD Grafik | Win11 Home | QWERTZ | grau | 3 Monate Premium Care            Lenovo                      Intel Core i5-12450H    16.0       512.0      Intel UHD Graphics     622.21
B08369D1K4       Acer Aspire 17 | Laptop | Intel Core 5 | 16GB | 512GB | mit Netzteil | 17" FHD IPS Display | Intel Core 5 120U | 16GB RAM | 512GB SSD | Intel Grafik | Windows 11 | QWERTZ Tastatur | A17-51M-51UJ              Acer                         Intel Core 5 120U    16.0       512.0      Intel UHD Graphics     626.42
B0BRCVH2NB                                                   Acer TravelMate P2 | 15,6" FHD | Core 5 120U | RAM: 16GB | SSD: 500GB | Laptop in Pure Silver | beleuchtete Tastatur | Windows 11 Pro | Notebooktasche              Acer                         Intel Core 5 120U    16.0       500.0                 Unknown     650.00
B0GKGWG1X6                          Dell 16 Laptop - AMD Ryzen 7 250, 16GB RAM, 1TB SSD | 16" entspiegelt, AMD Radeon Grafik, Deutsch beleuchtete QWERTZ Tastatur, Fingerabdruckleser (Netzteil separat erhältlich)              Dell                           AMD Ryzen 7 250    16.0      1024.0     AMD Radeon Graphics     652.20
B0GFP5QXD7                                       HP 17 Business Laptop, Intel Core i5-120U, 16 GB DDR4 RAM, 512 GB PCIe SSD, 17.3" FHD (1920x1080) Display, Intel Graphics, QWERTZ Tastatur, Windows 11 Pro, Silber                HP                         Intel Core 5 120U    16.0       512.0      Intel UHD Graphics     652.20
B0F9YYDDFD                                Dell 15 Laptop DC15250 15.6" FHD (1920 x 1080) 120Hz, Intel Core i7-1355U, Intel UHD Graphics, 16GB DDR4 RAM, 512GB SSD, Windows 11 Home, QWERTZ Backlit Keyboard - Black              Dell                       INTEL CORE i7-1355U    16.0       512.0      Intel UHD Graphics     679.00
B0D6GS2SLL                                                HP Pavilion Laptop, 16" WUXGA Touch-Display, AMD Ryzen 5 8540U, 8 GB DDR5 RAM, 512 GB PCIe NVMe SSD, AMD Radeon Graphics, QWERTZ, Windows 11 Home, Silber                HP                              Intel Core 5     8.0       512.0         AMD Radeon 740M     686.56
B0H27BDGFN                             Lenovo ThinkPad X1 Carbon Gen 10, Intel i5 10x1.6 GHz Prozessor, 32 GB Arbeitsspeicher, 512GB SSD, 14 Zoll Display, 1920 IPS, LTE, Cam, Windows 11 Pro G1A (Generalüberholt)    Amazon Renewed                       Intel Core i5-1245U    32.0       512.0           Intel Iris Xe     686.57
B0FJTVG363           Acer Aspire Go 15 | Laptop | Core 7 | 16GB | 1TB | mit Netzteil | 15,6" FHD IPS Display | Intel Core 7 150U | 16GB RAM | 1TB SSD | Intel Grafik | Windows 11 | QWERTZ Tastatur | AG15-72P-792F              Acer                         Intel Core 7 150U    16.0      1024.0        Intel Arc Grafik     686.57
B0GTVQL3DW                                  Laptop 18,5 Zoll FHD Display, 16GB RAM 256GB SSD AI-Unterstützung | Core I3, WiFi 6, Vollfunktions Type-C, Deutsche Tastatur Ideal für Studium, Homeoffice und Business            Liuord                    Intel Core 5 Prozessor    16.0       256.0       AMD Radeon Grafik     687.42
B0HBB9Z9GS                      18,5 Zoll Laptop AI-Unterstützung 16GB RAM 256GB SSD | Win 11, 8000mAh Akku, WiFi6, Full-HD, 180° Drehung Vollfunktions Type-C, HDMI, Deutsche Tastatur Ideal für Studium, Business           MELIUNA                                   Unknown    16.0       256.0                 Unknown     687.42
B0GTQQ3QWN          Laptop 18,5 Zoll 16GB RAM 256GB SSD, AI Unterstützung Notebook Core i3 (bis zu 3,9 GHz), 8000mAh Akku, Win 11, WiFi 6, FHD Display 180° Betrachtungswinkel, HDMI, USB-C Multifunktionsanschluss            Liuord                   Intel Core I3 Prozessor    16.0       256.0 NVIDIA GeForce RTX 5060     687.42
B0F225DQ9V                                                         Dell Latitude 5420/ Core i5 1145G7 2.6GHz / 16GB RAM / 256GB SSD/WiFi/BT / 14.0 FHD (1920x1080) / Win 11 Pro (Generalüberholt) (QWERTZ - German)    Amazon Renewed                      Intel Core i5 1145G7    16.0       256.0      Intel UHD Graphics     687.43
B0D5CZL3NN                              HP EliteBook 1040 G11 14 Zoll (35,6 cm) WUXGA Display, Intel Core Ultra 5 125H, 16GB LPDDR5x RAM, 512GB SSD, Intel Arc Grafik, LTE, QWERTZ Tastatur, Windows 11 Pro, Silber                HP                   Intel Core Ultra 5 125H    16.0       512.0        Intel Arc Grafik     691.81
B0CYQ4Q821 HUAWEI MateBook 14 Laptop,14.2" 2,8 K OLED Handschrift-Bildschirm mit Touchsteuerung, Ultraschlankes Design, Intel Core Ultra 5, 16GB+512GB, 19Hr Continuous Video Playback, Windows 11 Home, Space Grau            HUAWEI Intel Core Ultra 5 Prozessorgeschwindkeit    16.0       512.0           Intel Iris Xe     695.98
B0GK96SLMR       HP OmniBook 3 Laptop, 17,3" FHD, AMD Ryzen AI 7, 16GB RAM, 512GB SSD | Copilot+ KI-Notebook mit großem Display für produktives Multitasking, Office und Streaming - ohne Ladegerät, QWERTZ, Silber                HP                    AMD Ryzen AI Prozessor    16.0       512.0       AMD Radeon Grafik     699.00
B0DVCBX2QN                                                                               HP Laptop 17,3 Zoll IPS Full-HD, Intel Core i5 1334U, 10 x 4.60 GHz, 16 GB RAM, 512 GB SSD, Norton 360, Silber, Windows 11                HP                    Intel Core 5 Prozessor    16.0       512.0      Intel UHD Graphics     703.76
B0F1DJ8J6Y          HP OmniBook X Flip, 16" WUXGA, AMD Ryzen AI 5, 16GB RAM, 512GB SSD | Copilot+ Premium 2-in-1 Laptop für Kreativarbeit, Business und flexible Nutzung unterwegs - inkl. Netzteil, QWERTZ, Silber                HP                            AMD Ryzen AI 5    16.0       512.0         AMD Radeon 840M     708.92
B0B8H2J7H4              acer Aspire Spin 14 ASP14-52MTN-58CR Convertible Notebook 14 WUXGA LCD Touchscreen (Intel Core Ultra 5 115U, 16 GB RAM, 512 GB SSD, Intel Graphics, Windows 11 Home), Grau, QWERTY Spanisch              Acer                   Intel Core Ultra 5 115U    16.0       512.0      Intel UHD Graphics     711.96
B0FW5LZYTG       Acer Aspire 17 | Laptop | Intel Core 7 | 16GB | 512GB | mit Netzteil | 17" FHD IPS Display | Intel Core 7 150U | 16GB RAM | 512GB SSD | Intel Grafik | Windows 11 | QWERTZ Tastatur | A17-51M-77PV              Acer                              Intel Core 7    16.0       512.0         AMD Radeon 780M     712.35
B0CYQ4PK7X                            HUAWEI MateBook X Pro Core Ultra, 980 g Ultraleicht hautberuhigende Metallgehäuse, Intel Core Ultra 9 Prozessor, 14,2 Zoll OLED Real Colour Display, 32GB + 2TB, Morandi Blue            HUAWEI              Intel Core Ultra 9 Processor    32.0      2048.0       Intel Arc verfügt     712.35
B0HBC5M6XX                         Laptop 18,5 Zoll 16GB RAM 256GB SSD, AI Unterstützung Notebook | Core i3, 8000mAh Akku, Win 11, WiFi 6, FHD Display 180° Betrachtungswinkel, HDMI, USB-C Multifunktionsanschluss            Liuord                    Intel Core 5 Prozessor    16.0       256.0      Intel UHD Graphics     716.64
B0H5PTG2TF        FIREBAT 16-Zoll-Gaming-Laptop, Ryzen 7 H255 Octa-Core (bis zu 4,9 GHz), 32 GB LPDDR5, 1 TB SSD, QHD-Display mit 2,5K-Auflösung und 120 Hz, WLAN 6, hintergrundbeleuchtete Tastatur, Metallgehäuse           FIREBAT                      Intel Core i7-13800H    32.0      1024.0         AMD Radeon 780M     723.52
B0G5BKWWBB                     Dell 14 Laptop - AMD Ryzen AI 7 350, 16GB RAM, 1TB SSD | 14" entspiegelt, AMD Radeon Grafik, beleuchtete QWERTZ Tastatur, Fingerabdruckleser, Copilot+ (Netzteil separat erhältlich)              Dell                            AMD Ryzen AI 7    16.0      1024.0       AMD RADEON GRAFIK     729.54
B0GSH67FDX                                           Lenovo ThinkPad T14 Gen 3 Intel i7 10x1.3 GHz 12.Gen 32 GB Arbeitsspeicher 512 GB SSD 14 Zoll Display WUXGA 1920x1200 IPS Windows 11 Pro X5S (Generalüberholt)    Amazon Renewed                       Intel Core i7-1265U    32.0       512.0           Intel Iris Xe     730.40
B0FNR87M5B               Acer Aspire 17 | Laptop | Intel Core 7 | 16GB | 1TB | QWERTY | 17" FHD IPS Display | Intel Core 7 150U | 16 GB RAM | 1 TB SSD | Intel Grafik | Windows 11 | QWERTY Tastatur | A17-51M-76CR              Acer                              Intel Core 7    16.0      1024.0           Intel Iris Xe     732.04
B0GK1RR1BH                  HP OmniBook 3 Laptop, 14" WUXGA, Snapdragon X, 16GB RAM, 512GB SSD | Leistungsstarkes KI-Notebook mit Copilot+ und extra langer Akkulaufzeit - kein Ladegerät enthalten, QWERTZ, Silber                HP                        Intel Core Ultra 5    16.0       512.0                 Unknown     733.00
B0DYDVFVTJ                                    Microsoft Surface Laptop, 13" | Snapdragon X Plus | 16GB RAM, 256GB SSD | 13" LCD Touchscreen | Copilot+ PC | Platin | Windows 11 Home | Neuestes Modell (1. Edition) Microsoft Surface                         Snapdragon X Plus    16.0       256.0                 Unknown     735.54